[workspace]
members = [".", "macro"]

[package]
name = "smart-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
smart-bench-macro = { version = "0.1.0", path = "./macro" }
async-std = { version = "1.10.0", features = ["attributes", "tokio1"] }
color-eyre = "0.6.0"
codec = { package = "parity-scale-codec", version = "3", default-features = false }
contract-metadata = { package = "contract-metadata", git = "https://github.com/paritytech/cargo-contract", branch = "master" }
serde_json = "1.0.79"
clap = { version = "3.1.6", features = ["derive"] }
subxt = "0.18.0"
futures = "0.3.21"

# substrate
sp-core = "6.0.0"
sp-keyring = "6.0.0"
sp-runtime = "6.0.0"
